### ISSUE TITLE
not working in windows 10

### ISSUE THREAD

**Issue by Oxicode** [fterrag/vscode-php-cs-fixer#2]

**Comment by fterrag** [comment]
Hi @Oxicode! Thank you for creating an issue. Do you happen to have any specific information to share around the problem you're seeing in Windows 10?

**Comment by fterrag** [comment]
@Oxicode I found and resolved an issue that was preventing the extension from working on Windows. Thanks for the heads up!

**Comment by samayo** [comment]
how do you run this extension? I just installed it and then what?

**Comment by fterrag** [comment]
@samayo after installing the extension and reloading the editor, PHP files will automatically be formatted on save. Let me know if you run into any issues.

**Comment by samayo** [comment]
@fterrag thanks, it works but i have 1 question. why is code indented like this?
```php
public function isGet(): bool
{
    return $this->getMethod() === 'GET';
}
```
The return is indented by two spaces instead of 1. I can't fix it since it automatically indents the code by itself

thanks for making this ext btw

**Comment by fterrag** [comment]
@samayo the return in your example is indented by 4 spaces per PSR-2: https://www.php-fig.org/psr/psr-2/#1-overview (see the second bullet).
