### ISSUE TITLE
Not working in sub directories

### ISSUE THREAD

**Issue by rahulv3a** [fterrag/vscode-php-cs-fixer#4]
I have a custom `.php_cs` in the root directory of my project.  The extension works great in the root directory. But when I save a file in any sub directory, it throws an error. In the console in Developer Tools it says:
```
In ConfigurationResolver.php line 567:
   Cannot read config file ".php_cs".  
```
I have the following in the settings:
```json
"vscode-php-cs-fixer.config": ".php_cs",
"vscode-php-cs-fixer.fixOnSave": true,
```

P.S. Thank you for your work. This is the only PHP CS fixer extension that I could get to work.

**Comment by sergejostir** [comment]
`        args.push('--config=' + path.join(vscode.workspace.rootPath, config))`
Put this on line 32 in extension.js and you are good to go until it's officially fixed ;)

**Comment by abraaoz** [comment]
> ` args.push('--config=' + path.join(vscode.workspace.rootPath, config))`
> Put this on line 32 in extension.js and you are good to go until it's officially fixed ;)

This solution does not work on multi-folder workspaces. [A more definitive solution](https://github.com/fterrag/vscode-php-cs-fixer/pull/10) has been proposed to the plugin author, but pull has yet to be accepted to become official.

**Comment by abraaoz** [comment]
@fterrag accepted the pull request. This issue should be marked as resolved.
