### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ahmadtareq63** [fterrag/vscode-php-cs-fixer#7]
[fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt](https://github.com/fterrag/vscode-php-cs-fixer/files/3345710/fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-php-cs-fixer`
- Extension Version: `0.3.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.35.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt](https://github.com/fterrag/vscode-php-cs-fixer/files/3345714/fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt)
[fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt](https://github.com/fterrag/vscode-php-cs-fixer/files/3345716/fterrag.vscode-php-cs-fixer-unresponsive.cpuprofile.txt)

**Comment by fterrag** [comment]
@Ahmadtareq63 are you able to provide any additional information?
