### ISSUE TITLE
How to configure for Travis CI

### ISSUE THREAD

**Issue by blachawk** [fterrag/vscode-php-cs-fixer#8]
Is there a way configure rules with this extension?  I am trying to match the same Travis CI rules in Github for a project I am working on, to this extension.  It apears that what vscode php-cs-fixer see's as right, is different from what Travis CI on GitHub see's at right. 

Please show me how I can bridge gap.

Thanks!

**Comment by fterrag** [comment]
Hi @blachawk,

I'm not entirely sure if I understand what you're asking for, but you may want to create a .php_cs file per https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file. This will allow you to configure php-cs-fixer as needed.

Let me know if this makes sense.

Thanks!
