### ISSUE TITLE
Php 7.4

### ISSUE THREAD

**Issue by sineld** [fterrag/vscode-php-cs-fixer#9]
Please update included php-cs-fixer and add @PSR7 compatibility.
Thanks.

**Comment by stanislavdavid** [comment]
You can use whatever version of php-cs-fixer you want. You can add to settings.json:

` "vscode-php-cs-fixer.toolPath": "/path/to/bin/php-cs-fixer",`

**Comment by fterrag** [comment]
Thanks for the heads up on this! I'll be pushing an update to the extension over the next day or two.

**Comment by abraaoz** [comment]
A pull request was made for this: https://github.com/fterrag/vscode-php-cs-fixer/pull/11
Waiting for @fterrag approval

**Comment by mludi** [comment]
I'd love to see this feature soon.

**Comment by WoLfulus** [comment]
Waiting for this too

**Comment by mgmgpyaesonewin** [comment]
+1

**Comment by wsamoht** [comment]
While we wait for https://github.com/fterrag/vscode-php-cs-fixer/pull/11 to get merged, if you need to use this extension with PHP 7.4, go ahead and download/install php-cs-fixer  following the directions here - https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation.

Then under the php-cs-fixer extension settings, set the "Tool Path" to where you installed PHP CS Fixer. I installed it globally with Composer so my path is `/home/USERNAME/.composer/vendor/bin/php-cs-fixer`.

**Comment by niagarafallstourism** [comment]
Has anyone tried this on Windows 10? I changed my setting to
`C:\\Users\\USERNAME\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer`
also tried with .bat file. Neither worked, the error about PHP7.4 is gone, but now nothing happens. No log, no formatting.

**Comment by fterrag** [comment]
php-cs-fixer has been updated to the latest version.
